// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAqUuN4SaXW4TSCtMKO5eo42b_7x9q7h9c",
    authDomain: "cricball.firebaseapp.com",
    projectId: "cricball",
    storageBucket: "cricball.firebasestorage.app",
    messagingSenderId: "994903842997",
    appId: "1:994903842997:web:1f8c7e00a4790207ce1efc",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAqUuN4SaXW4TSCtMKO5eo42b_7x9q7h9c",
    appId: "1:994903842997:android:1f8c7e00a4790207ce1efc",
    messagingSenderId: "994903842997",
    projectId: "cricball",
    storageBucket: "cricball.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAqUuN4SaXW4TSCtMKO5eo42b_7x9q7h9c",
    appId: "1:994903842997:ios:1f8c7e00a4790207ce1efc",
    messagingSenderId: "994903842997",
    projectId: "cricball",
    storageBucket: "cricball.firebasestorage.app",
  );
}
